### ISSUE TITLE
Dependency on Windows version

### ISSUE THREAD

**Issue by KamilZm** [jechtom/global#1]
On my computer (Windows 10 v1903 + .NET 4.8) script doesn't work because [there is dependency](https://docs.microsoft.com/cs-cz/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed) between **Release** property value in registry and Windows version. 

For example NET 4.8:
- Windows 10 May 2019 Update: **528040**
- all others Windows operating systems (including other Windows 10 operating systems): **528049**

<img width="494" alt="2019-08-27_13h05_07" src="https://user-images.githubusercontent.com/7085032/63766452-764a2e00-c8cb-11e9-9f90-be9ff5459775.png">
<img width="358" alt="2019-08-27_13h05_44" src="https://user-images.githubusercontent.com/7085032/63766453-764a2e00-c8cb-11e9-9307-011d9fea0610.png">

**Comment by jechtom** [comment]
Fixed. Thanks for reporting. I am now using lowest version to identify installed framework.
